# Generated by Django 5.1.5 on 2025-01-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='public_id',
            field=models.CharField(help_text='Used to retrieve the image itself. Should not be readable until the image is attached to another object.', max_length=255, unique=True),
        ),
    ]
