# Generated by Django 5.1.5 on 2025-01-17 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_operation', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.office')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
                ('turma', models.CharField(choices=[('1info1', '1info1'), ('1info2', '1info2'), ('1info3', '1info3'), ('2info1', '1info1'), ('2info2', '1info2'), ('2info3', '1info3'), ('3info1', '1info1'), ('3info2', '1info2'), ('3info3', '1info3'), ('1agro1', '1agro1'), ('1agro2', '1agro2'), ('1agro3', '1agro3'), ('2agro1', '2agro1'), ('2agro2', '2agro2'), ('2agro3', '2agro3'), ('3agro1', '3agro1'), ('3agro2', '3agro2'), ('3agro3', '3agro3'), ('1quimi', '1quimi'), ('2quimi', '2quimi'), ('3quimi', '3quimi')], max_length=6)),
                ('curso', models.CharField(choices=[('informatica', 'Informatica Para Internet'), ('quimica', 'Quimica'), ('agropecuaria', 'Agropecuaria')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
