# Generated by Django 5.1.5 on 2025-01-18 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_office_guildmember_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuildMember',
            new_name='GuildMemberData',
        ),
        migrations.RenameField(
            model_name='guildmemberdata',
            old_name='year_operation',
            new_name='year_active',
        ),
        migrations.RemoveField(
            model_name='guildmemberdata',
            name='user',
        ),
        migrations.AddField(
            model_name='guildmemberdata',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_guild_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
