# Generated by Django 5.1.5 on 2025-01-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_guildmember_guildmemberdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmemberdata',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.office'),
        ),
        migrations.AlterField(
            model_name='guildmemberdata',
            name='year_active',
            field=models.IntegerField(auto_created=True),
        ),
    ]
