# Generated by Django 5.1.5 on 2025-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_guildmemberdata_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_guild_member',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
