# Generated by Django 5.1.5 on 2025-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_student_is_guild_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmemberdata',
            name='year_active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.CharField(choices=[('1info1', '1info1'), ('1info2', '1info2'), ('1info3', '1info3'), ('2info1', '2info1'), ('2info2', '2info2'), ('2info3', '2info3'), ('3info1', '3info1'), ('3info2', '3info2'), ('3info3', '3info3'), ('1agro1', '1agro1'), ('1agro2', '1agro2'), ('1agro3', '1agro3'), ('2agro1', '2agro1'), ('2agro2', '2agro2'), ('2agro3', '2agro3'), ('3agro1', '3agro1'), ('3agro2', '3agro2'), ('3agro3', '3agro3'), ('1quimi', '1quimi'), ('2quimi', '2quimi'), ('3quimi', '3quimi')], max_length=6),
        ),
    ]
