# Generated by Django 5.1.6 on 2025-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_guild_member',
        ),
        migrations.AddField(
            model_name='guildmemberdata',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guildmemberdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
