# Generated by Django 5.1.6 on 2025-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_student_is_guild_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
