# Generated by Django 5.1.6 on 2025-02-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_office_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmemberdata',
            name='year_active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
