# Generated by Django 5.1.5 on 2025-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0006_replieofreplie'),
    ]

    operations = [
        migrations.AddField(
            model_name='replieofreplie',
            name='replyOfreply',
            field=models.TextField(default=None),
        ),
    ]
